# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Echo out the Variables for the log      
      write-host $env:B2CTENANTNAME $env:CLIENTCREDAPPID $env:ProxyIdentityExperienceFrameworkAppName $env:IdentityExperienceFrameworkAppName $env:B2CExtensionAttributeAppName $env:AppInsightInstrumentationKey 
      
      # build a dictionary of additional variables to replace in the B2C policy files      
      [hashtable]$params = @{"{config:Facebook:client_Id}"=$env:FACEBOOKCLIENTID; "{config:AppInsightInstrumentationKey}"=$env:AppInsightInstrumentationKey}

      # run the deployment script that modifies the policies and then uploads them
      .\scripts\prepare-b2c-policies.ps1 -PolicyPath .\policies -PolicyPrefix $env:B2CPolicyPrefix -TenantName $env:B2CTENANTNAME -AppID $env:CLIENTCREDAPPID -AppKey $(CLIENTCREDAPPKEY) -ProxyIdentityExperienceFrameworkAppName $env:ProxyIdentityExperienceFrameworkAppName -IdentityExperienceFrameworkAppName $env:IdentityExperienceFrameworkAppName -B2CExtensionAttributeAppName $env:B2CExtensionAttributeAppName -ConfigKeyValues $params

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/policies'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/policies'
    CleanTargetFolder: true
    OverWrite: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/scripts'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/scripts'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'